### ISSUE TITLE
problem on build caused by this module

### ISSUE THREAD

**Issue by Reza-Ghz** [exponent/freeport-async#2]
when i use `expo build:android` command to build these errors appears:
```
➜  AwesomeProject expo build:android
[19:02:48] Making sure project is set up correctly...
[19:02:55] Your project looks good!
[19:02:55] Checking if current build exists...

[19:03:00] No currently active or previous builds for this project.

? Would you like to upload a keystore or have us generate one for you?
If you don't know what this means, let us handle it! :)
 false
[19:03:07] Unable to find an existing Expo CLI instance for this directory, starting a new one...
(node:16625) UnhandledPromiseRejectionWarning: RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 65536.
    at Server.listen (net.js:1412:13)
    at /usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:8:12
    at new Promise (<anonymous>)
    at testPortAsync (/usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:6:10)
    at /usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:27:23
    at new Promise (<anonymous>)
    at freePortRangeAsync (/usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:23:10)
    at /usr/local/lib/node_modules/expo-cli/node_modules/freeport-async/index.js:33:18
(node:16625) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16625) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
can you tel me whats the problem?

**Comment by ide** [comment]
It's possible that you got unlucky and it randomly chose a port out of range, in which case you can try again. Or if you consistently get this error, it's likely an issue with your computer not having any free ports and you'll need to figure out the specific way to fix that.
